### ISSUE TITLE
index/images

### ISSUE THREAD

**Issue by crecorn** [Sterc/seosuite#3]
When I add the property &type to SeoSuiteSitemap with either images or index no pages are returned. It works without it.

**Comment by sdrenth** [comment]
@crecorn Here's an example setup:

This is the resource structure
![Screenshot 2021-01-22 at 09 59 31](https://user-images.githubusercontent.com/7802465/105469459-8e78d500-5c98-11eb-8460-b2d330b2787d.png)

Sitemap Index:
[[!SeoSuiteSitemap? &type=`index`]]

Google Sitemap:
[[!SeoSuiteSitemap]]

Image Sitemap:
[[!SeoSuiteSitemap? &type=`images`]]

Please note that the "Include this page in the sitemap?" needs to be checked for every resource in order to show in the sitemap. 

The image sitemap works based on image TV values.

**Comment by ilyautkin** [comment]
Checked: ```[[!SeoSuiteSitemap? &type=`index`]]``` and ```[[!SeoSuiteSitemap? &type=`images`]]``` works correct in last version.
