### ISSUE TITLE
Hide the module in some resources!

### ISSUE THREAD

**Issue by frommax** [Sterc/SEOSuite#81]
Why don't you want to add your SEO Suite module in Forms Setup -> Profile -> Rule Set -> Areas (/manager/?a=security/forms/set/update&id=1)? I already clarified about 4 years ago regarding this issue. There are some templates for which I would like to disable the display of your module when editing a resource. All other modules disable correctly, but your module does not. I am creating a resource and template "settings" for the settings of the entire site, I need to display only TV-fields in the editing of the resource, everything else, including your module I want to hide.  https://prnt.sc/WfPoz7pqDIRz

**Comment by joeke** [comment]
@frommax There is a system setting `seosuite.disabled_templates` where you can add a comma-separated list of template IDs which will then not show Seo Suite for those templates, so that will solve your problem as well.
If you really want to add it to Form Customization you're welcome to supply us with the code changes needed for it in a pull request, and we will be happy to add it in the next release.
