### ISSUE TITLE
Can't uncheck “Include this page in the sitemap?”

### ISSUE THREAD

**Issue by lottaar** [Sterc/SEOSuite#97]
If I uncheck “Include this page in the sitemap?”, save the resource and then re-open the resource, it’s checked again. So there’s no way of excluding pages from the sitemap.

MODX 3.0.4-dev & SEO Suite 3.1.2.

**Comment by halftrainedharry** [comment]
The problem is probably caused by the changes in commit https://github.com/Sterc/seosuite/commit/9ab62243f77e83ac236a88cb576ea4af69d65cd6.

It seems that the POST parameter "seosuite_sitemap" is only sent, when the checkbox is checked. When the checkbox is unchecked, no parameter is sent and the value is reset to the default of 1.

**Comment by lottaar** [comment]
Good to know the cause. I hope a fix is released quickly so we can keep using the Extra, it's got some great functionality.
